### ISSUE TITLE
Lab 07 feedback

### ISSUE THREAD

**Issue by Sicheng2000** [Sicheng2000/lab-07#1]
1. · Acquire refers to getting data, curate is to tidy the data while keeping the original format though removing redundant or less informative variables, transform refers to tailoring datasets according to an individual's purpose when multiple datasets can be produced based on the curated datasets.
· In the normalization process, using `slice_sample()` to check artifacts in the datasets prevents individuals from checking datasets row by row.
· Tokenization is to change the unit of observations like text to sentence, sentence to phrases, words, and so on.
· `case_when` allows individuals to assign values according to different conditions.
· `count()` and `distinct()` can help to filter out some less informative values.
2. I think the most challenging aspect is constructing idealized datasets tailored to address my research questions. Because once I have a clear goal in mind, transforming datasets becomes more easy.
3. During this lab exercise, I found an interesting issue. When I attempted to execute the following code block: 
```{r}
#| label: sentiment-metadata-address-year

# Add the address_year
sotu_tbl <-
  sotu_tbl |>
  mutate(address_year = year(date))

# Preview
glimpse(sotu_tbl)
```
I received an error message stating:  
"Error in mutate():
ℹ In argument: date = as.Date(date).
Caused by error in as.Date.default():
! do not know how to convert 'date' to class “Date”". 
So I revised "date" to "Date" assuming it was a function, as indicated by `class()`. However, when I ran the entire Quarto document, I found the same error message "Caused by error in as.POSIXlt.default()". I then reverted "Date" back to "date", and the code executed successfully. This led me to wonder why the error occurred, given that "date" is indeed a function. Upon checking the `sotu_tbl`, I noticed that the variable name was "Date" rather than "date". ChatGPT suggested I check the "date" format, but it did not explain the question. For subsequent processes, I primarily relied on https://qtalr.github.io/qtalrkit/articles/recipe-7.html.
5. I may want to explore methods for collaborating with other datasets to enrich my datasets. I noticed that  Professor @francojc collaborating with a sentiment dataset called `bing_lexicon` to annotate his datasets. This prompted me to think about how to identify suitable datasets efficiently, perhaps by leveraging Google search. However, I encountered challenges when attempting to find a relevant community interpreting corpus in Mandarin through Google search. To learn more about data transformation, I found a video tutorial (https://www.youtube.com/watch?v=5571wc0iWCI) where the presenter utilized plots to aid in data normalization. For instance, he mentioned that if the tail of the plot appears excessively long, it may indicate the need for data filtering or adjustments to enhance its analytical suitability.

**Comment by francojc** [comment]
For the `data` column. It's helpful to preview the tibble and see if the `date` column is of type <date>. If so, there should be no issue.
